### ISSUE TITLE
[BUG] Typing error with Field q kwarg

### ISSUE THREAD

**Issue by jam13** [vitalik/django-ninja#1037]
**Describe the bug**
Filtering docs (https://django-ninja.dev/guides/input/filtering/) describe passing q string to Field definition:
```python
class BookFilterSchema(FilterSchema):
    name: Optional[str] = Field(None, q='name__icontains') 
``` 

I had this working fine, but following package updates (including mypy to 1.7) it is failing type checking:
```
src/foo.py:23: error: Unexpected keyword argument "q" for "Field"  [call-arg]
/opt/venv/lib/python3.11/site-packages/pydantic/fields.py:673: note: "Field" defined here
Found 1 error in 1 file (checked 123 source files)
```

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2
 - Django-Ninja version: 1.1.0
 - Pydantic version: 2.5.3

**Comment by OtherBarry** [comment]
Are you importing `Field` from `ninja` or `pydantic`?

**Comment by jam13** [comment]
> Are you importing `Field` from `ninja` or `pydantic`?

`ninja`

```python
from ninja import Field, FilterSchema


class FooFilterSchema(FilterSchema):
    project_id: Optional[UUID] = Field(q="project_id")
```

**Comment by vitalik** [comment]
@jam13 

that's weird - as you can see in tests it's used just fine:

https://github.com/vitalik/django-ninja/blob/master/tests/test_filter_schema.py

maybe you mixed some imports ? May be you forced deprecation warnings to throw errors  (warnings.simplefilter) ?

**Comment by jam13** [comment]
> @jam13
> 
> that's weird - as you can see in tests it's used just fine:
> 
> https://github.com/vitalik/django-ninja/blob/master/tests/test_filter_schema.py
> 
> maybe you mixed some imports ? May be you forced deprecation warnings to throw errors (warnings.simplefilter) ?

I'll check it again and see if it's still an issue.

**Comment by jam13** [comment]
> > @jam13
> > that's weird - as you can see in tests it's used just fine:
> > https://github.com/vitalik/django-ninja/blob/master/tests/test_filter_schema.py
> > maybe you mixed some imports ? May be you forced deprecation warnings to throw errors (warnings.simplefilter) ?
> 
> I'll check it again and see if it's still an issue.

Still getting the same error.

I've checked and I'm not importing Field directly from pydantic anywhere in the code.

Not knowingly forced deprecation warnings to throw errors.

My mypy config is:
```toml
[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_any_generics = true
#disallow_any_unimported = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
#disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
#show_error_codes = true
strict_equality = true
warn_redundant_casts = true
#warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
exclude = [
    "src/v1/migrations",
]
plugins = [
    "mypy_drf_plugin.main",
    "mypy_django_plugin.main",
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin",
]
```
